### PR TITLE
Update Parser to reduce crud

### PR DESCRIPTION
**Pull request by flooie**
Remove unnecessary dependencies to main method and split out to development

### CODE REVIEW

**Comment by mlissner** [comment]
Why does this have a readme.md and a readme.rst? 

Also: Not loving poetry?

**Comment by flooie** [comment]
I really haven't found poetry to be my cup of tea.  The MD file should be dropped at some point.

**Comment by flooie** [comment]
@mlissner I'm also trying to speed this forward so I can move onto the next big thing.

**Comment by mlissner** [comment]
That's too bad. Poetry and I just re-upposed our vows yesterday as I moved django-ses over to using it:

https://github.com/django-ses/django-ses/pull/238

I like how much more strict it is than pip, and it's got a lot of momentum behind it. It can be slow, yes, but the slowness is something that pip *should* be doing and is just being bad about. Ah well, low stakes here. We can discuss eventually.

**Pull request merged**
